<h3>Welcome in JXcore module for Plesk!</h3>
<br>
The JXcore will be downloaded now and installed.
<br>
<br>
<span style="color: orangered">
The Apache's <b>mod_proxy</b> module needs to be enabled and this may require Apache service to be restarted.
</span>
<br>
<br>
<span style="color: orangered; text-decoration: underline">
Please note, that even if you will disable <b>mod_proxy</b> manually, JXcore will enable it each time JXcore monitor starts.
</span>

<br>
<br>
Click OK, if you agree with that.
<br>

<?php echo $this->form; ?>