<?php echo $this->messages; ?>
<img src="http://jxcore.com/jxcore.png" width="140px" />
<br/>
<br/>
<br/>
This software extends Plesk with JXcore for Node Applications.
In order to provide a seamless Node experience, the software may update the server configuration for domains.
<br/>
<br/>
- Enables NGINX for Parallel's Plesk
<br/>
<br/>
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
<br>
<br>
Click OK, if you are agree with the terms above.
<br>

<?php echo $this->form; ?>